---
- name: Gracefully shutting down cassandra nodes
  hosts: all
  become_method: sudo
  gather_facts: false
  tasks:
    - name: Initiate graceful shutdown by nodetool flush and drain
      shell: "nodetool {{item}} && sleep 5"
      with_items:
        - flush
        - drain
    - name: Stop Cassandra service
      service:
        name: cassandra
        state: stopped
    - name: rebooting {{ inventory_hostname }}
      ignore_errors: yes
      shell: /sbin/reboot
    - name: Start Cassandra Service
      service:
        name: cassandra
        state: started
    - name: Pause of 3 mins after boot up
      pause:
        seconds: 180
    - name: Check the Status of the Node
      shell:  nodetool status | grep -w {{ inventory_hostname }} > /tmp/output; awk '{print}' /tmp/output
      register: nodetool_status
      failed_when: nodetool_status.stdout != "UN"
    - debug: var={{ item }}
      with_items:
        - nodetool_status.stdout_lines