---
- hosts: all
  serial: 1

  tasks:
    - name: reboot host
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0
      become: true
      
    - name: Pausing for Service to Get up Properly
      pause:
        minutes: 12
