---
- name: Security Updates Playbook
  hosts: all
  tasks:
    - name: Update Cache
      apt:
        update_cache: yes
      
    - name: Running security upgrades (unattended upgrades)
      shell: unattended-upgrades -v
      
      

 
