---
- name: Security Updates Playbook
  hosts: all
  tasks:
    - name: Check Updates
      shell: apt update
      become: true
      
    - name: Running security upgrades (unattended upgrades)
      shell: unattended-upgrades
      become: true

 
