---
- name: Update_All_Packages
  hosts: all
  tasks:
   - name: Update all packages to the latest version
     apt:
       upgrade: dist
       
   - name: Remove dependencies that are no longer required
     apt:
       autoremove: yes
     


 
